# Generated by Django 6.0.4 on 2026-04-30 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reteta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=200)),
                ('ingrediente', models.TextField()),
                ('instructiuni', models.TextField()),
                ('data_adaugare', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
