# Generated by Django 6.0.4 on 2026-04-30 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retetele', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reteta',
            old_name='instructiuni',
            new_name='preparare',
        ),
        migrations.RemoveField(
            model_name='reteta',
            name='data_adaugare',
        ),
    ]
