# Generated by Django 6.0.4 on 2026-05-01 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retetele', '0003_rename_reteta_retete'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='retete',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='poze_retete/'),
        ),
        migrations.AddField(
            model_name='retete',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retete', to=settings.AUTH_USER_MODEL),
        ),
    ]
