# Generated by Django 6.0.4 on 2026-05-01 18:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retetele', '0004_retete_image_retete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='retete',
            name='data_creare',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='retete',
            name='poza',
            field=models.ImageField(default='default.jpg', upload_to='poze_retete/'),
        ),
        migrations.AddField(
            model_name='retete',
            name='timp_gatire',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='retete',
            name='timp_pregatire',
            field=models.TextField(blank=True, null=True),
        ),
    ]
