# Generated by Django 6.0.4 on 2026-05-01 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retetele', '0005_retete_data_creare_retete_poza_retete_timp_gatire_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retete',
            name='image',
        ),
        migrations.AlterField(
            model_name='retete',
            name='poza',
            field=models.ImageField(blank=True, null=True, upload_to='poze_retete/'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reteta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='retetele.retete')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reteta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='retetele.retete')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('reteta', 'user')},
            },
        ),
    ]
