# Generated by Django 6.0.4 on 2026-05-01 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retetele', '0006_remove_retete_image_alter_retete_poza_comment_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='retete',
            name='categorie',
            field=models.CharField(choices=[('MD', 'Mic dejun'), ('PR', 'Prăjituri'), ('TO', 'Torturi'), ('SU', 'Supe și ciorbe'), ('GA', 'Garnituri'), ('CA', 'Carne'), ('PE', 'Pește')], default='mic_dejun', max_length=30),
        ),
    ]
